version: "3"
services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    image: "bitnami/kafka:latest"
    container_name: "kafka-1"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.68:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-2:
    image: "bitnami/kafka:latest"
    container_name: "kafka-2"
    ports:
      - "19092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.68:19092
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-3:
    image: "bitnami/kafka:latest"
    container_name: "kafka-3"
    ports:
      - "29092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.68:29092
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
