services:
  oraclefree:
    image: gvenzl/oracle-free:23
    container_name: oracle-xe-23
    volumes:
      - oracle-volume:/opt/oracle/oradata
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      APP_USER: "laboratorio"
      APP_USER_PASSWORD: "laboratorio"
      ORACLE_PASSWORD: "1234"

    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  oracle-volume:
