services:
  mongodb:
    image: mongo:8.2.7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - /data/db:/data/db
      - ./mongod.conf:/etc/mongod.conf  # Monta el archivo de configuración
    command: mongod --config /etc/mongod.conf  # Usa el archivo de configuración

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb 
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:1234@mongodb:27017/
