# Límites de conexión
connection_max = 1000
channel_max = 2047

# Memoria y disco
vm_memory_high_watermark.relative = 0.4
disk_free_limit.relative = 1.0

# Performance
collect_statistics_interval = 30000
heartbeat = 60

# Logging
log.console.level = info
log.file.level = warning
